name: ci-cd
on:
  push:
    branches:  ["main"] # não é recomendado fazer na main, só pra testes
  workflow_dispatch:
  
jobs:
  ci:
    runs-on: ubuntu-latest   #runner
    steps:
      - run: echo "obter código"
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Setup dp .NET core
        uses: actions/setup-dotnet@v3.4.2
        with:
            dotnet-version: 8.x


      - name: Executar testes
        working-directory: 02-review/src/Review-Filmes.Test.Unit
        run: dotnet test

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push da imagem Docker
        uses: docker/build-push-action@v6
        with: #parametros
          # nome da imagem
          tags: 
            mauricioaalmeida/maa-teste:v${{ github.run_number }}
            mauricioaalmeida/maa-teste:latest
            # contexto
          context: ./02-review/src
          # dockerfile
          
          file: .02-review/srv/Review-Filmes.Web/Dockerfile
          push: true
          

      - run: echo "Push da imagem Docker"
      
  cd:
    needs: [ci] # só roda depois de rodar o ci
    runs-on: ubuntu-latest   # runner
    steps:
      - run: echo "obter código"
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - run: echo "configurar o kubeconfig" # Kubernet set context
      - name: Configurar o kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: executar o apply
        uses: Azure/k8s-deploy@v5
        with:
          manifest:
            ./02-review/k8s/deployment.yaml
          images:
            mauricioaalmeida/maa-teste:v${{ github.run_number }}
      
      - run: echo "Executar o apply"
